name: ci
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TEST_API_URL: ${{ secrets.TEST_API_URL }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run test
      - run: npm run test:types
      - run: npm run coverage
