name: ci
'on':
  pull_request:
    branches:
      - main

env:
  TEST_API_URL: ${{ secrets.TEST_API_URL }}

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run test:types
      - run: npm run test
